### ISSUE TITLE
cant open files... PCB program says error in file

### ISSUE THREAD

**Issue by QuackenAudio** [adafruit/Adafruit-Analog-Accelerometers-PCBs#2]
none of these files open properly

can I have a raw text output version that I can paste into a file and rename as brd so my PCB program can open it?

looking for an adxl335

**Comment by ladyada** [comment]
Eaglecad can open it, or you can import into kicad

**Comment by QuackenAudio** [comment]
![image](https://user-images.githubusercontent.com/51548286/108653795-3e9a5300-747c-11eb-88d9-fe4719138ed0.png)


it doesnt open...
sorry...
and Eagle is not free...
please save in a format that can be opened by other programs

**Comment by QuackenAudio** [comment]
![image](https://user-images.githubusercontent.com/51548286/108653874-6b4e6a80-747c-11eb-8477-d34f37fa9584.png)
